### PR TITLE
Support placing images in-line with text

### PR DESCRIPTION
**Pull request by smallsco**
This PR allows you to place images in-line with text, like so:

```lua
text = Text(20, 20, 'Hello, [  ](smiley) World!', {
    font = love.graphics.newFont(48),
    smiley = love.graphics.newImage('smiley.png')
})
```

The space reserved for the image is equal to the space reserved for the characters inside the square brackets. It is up to the user to ensure that they reserve an appropriate amount of space, and that the image is appropriately sized both horizontally and vertically.

Functions can be used to manipulate images in the same way that they can be used to manipulate text. For example, using the shake function from the documentation, we can shake the image:

```lua
text2 = Text(20, 100, 'Hello, [  ](smiley;shake) World!', {
        font = love.graphics.newFont(48),
        smiley = love.graphics.newImage('smiley.png'),
        shakeInit = function(c)
            c.anchor_x = c.x
            c.anchor_y = c.y
        end,
        shake = function(dt, c)
            c.x = c.anchor_x + c.position*math.random(-1, 1)/2
            c.y = c.anchor_y + c.position*math.random(-1, 1)/2
        end
    })
```

Images are added to the character table as "c.image" so that you can directly access the image object from functions (for example, to get its' height or width). I have also added a "customDrawImage" function that works identically to the existing "customDraw".

Example:
Example

### CODE REVIEW

**Comment by adonaac** [comment]
Wow this seems crazy cool. I'll take a look at it soon (don't have time now). But just a question, what happens when you have multiple lines and the image has a bigger height than the line height? Does the image "go over" the next line or is the next line pushed down to respect the image height? I just wanna know for curiosity either situation is fine! :smile:

**Comment by davisdude** [comment]
Also, it seems like it would be useful to add an option that changes given the image attributes. That way you could have the text dynamically change if you scale an image, or something like that...

**Comment by smallsco** [comment]
@adonaac If the image is bigger than the line height, the next line of text is drawn overtop of the image. Popo reserves the normal amount of space for the characters you put inside the square brackets, the only change here is that if we have an Image object instead of a function or font, we print that image instead (and only print it once).

@davisdude You have access to c.image in the character table, so you can write functions to transform the image there. But it's not possible to make the text dynamically adapt to that, I think, without a significant rewrite of the underlying code (at the very least, popo would have to see the image as a "character" itself instead of as a "character-transforming function").

**Comment by adonaac** [comment]
>I think, without a significant rewrite of the underlying code (at the very least, popo would have to see the image as a "character" itself instead of as a "character-transforming function").

I've been meaning to rewrite this for a while now to make the code easier to maintain and change. I've been thinking of instead of doing parsing myself (making sure that this "[asdasd](asdasdj)" works), I can just do something like: text = Text(x, y, {'color', {color = {255, 23, 122}}, 'function', {function(c, dt) c*dasash end}, {image = some image}}) and then internally it just binds this all together and prints it out with the appropriate tags added.

When I do this I'll make sure to take images into account and to make it easy to dynamically change the text too based on their width/height. Do you have any other ideas/requests that you'd like to see? If you have some then it'd be nice for me to know so I can start thinking about what I have to accommodate for

**Comment by smallsco** [comment]
One feature that I'd really like is the ability to append additional text to an already existing object. I'm working on a textbox library for a game, using popo internally. I've managed to implement it by destroying and recreating the underlying popo object, and modifying the "typewriter effect" function to take a starting character position - which works fine, though I wonder if it could cause memory leaks over time.

Another nice-to-have would be the ability to set a maximum number of lines, and not have popo draw any additional text that exceeds it (bonus points if I could extract the undrawn portion of the string). I could probably do this myself in the box library though by using a scissor (except for the bonus points bit).

The image code I've implemented here is very naive - if you want to adjust the positioning or scale, you have to write another function to do it for each image (or use the custom draw, but that applies to all images) - so maybe a way to specify that when defining the image would be useful.

Last but not least - with your new syntax, it looks like it's not possible to nest functions? This unfortunately is a dealbreaker for me, I rely on that behavior in order to make my textbox work:
`text = new Text(10,10,'[This is [[some](red) text](shake)](typewriter)')`
(after appending:)
`text = new Text(10,10,'This is [[some](red) text](shake) [Some [more](blue) text](typewriter:18)')`

Anyway, we're going off-topic ;) Give the image code a try when you have some time! I admit it has its' drawbacks, but I think it will cover the 80% use case.

**Comment by adonaac** [comment]
> it looks like it's not possible to nest functions?

I think you can build nesting on top of it by dividing each part and just doing it manually. Because it would be only tables + text this would be easier to do programmatically than it is now.

**Pull request merged**
